# AlgoKit template generation answers
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 73c4f82
_src_path: https://github.com/barnjamin/algokit-beaker-playground-template
algod_port: '4001'
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
indexer_port: '8980'
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

